# Generated by Django 6.0.2 on 2026-03-19 09:06

import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=255)),
                ('house_number', models.CharField(blank=True, max_length=20)),
                ('apartment', models.CharField(blank=True, max_length=20)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('remark', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ems_code', models.CharField(help_text='FIFe EMS breed code (e.g., MCO)', max_length=10, unique=True, verbose_name='EMS code')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Breed',
                'verbose_name_plural': 'Breeds',
                'ordering': ['ems_code'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['country', 'region', 'translations__name'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ems_code', models.CharField(help_text='EMS color code (e.g., ns 22)', max_length=20, unique=True, verbose_name='EMS color code')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('remark', models.TextField(blank=True, verbose_name='Remark (for internal use)')),
            ],
            options={
                'verbose_name': 'Color',
                'verbose_name_plural': 'Colors',
                'ordering': ['ems_code'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ColorComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='EMS code')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Order in EMS formula')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('remark', models.TextField(blank=True, verbose_name='Remark (for internal use)')),
            ],
            options={
                'verbose_name': 'Color Component',
                'verbose_name_plural': 'Color Components',
                'ordering': ['type__order', 'order', 'code'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ColorComponentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Order in EMS formula')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('remark', models.TextField(blank=True, verbose_name='Remark (for internal use)')),
            ],
            options={
                'verbose_name': 'Color Component Type',
                'verbose_name_plural': 'Color Component Types',
                'ordering': ['order', 'code'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso_code', models.CharField(help_text='ISO 3166-1 alpha-2', max_length=2, unique=True)),
                ('phone_code', models.CharField(blank=True, max_length=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['iso_code'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='media/')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_public', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbreviation', models.CharField(max_length=20, unique=True, verbose_name='Аббревиатура титула')),
                ('title_type', models.CharField(choices=[('CHAMPION', 'Чемпион'), ('INTERCHAMPION', 'Международный чемпион'), ('NATIONAL', 'Национальный титул'), ('WORLD', 'Мировой титул'), ('OTHER', 'Другое')], default='OTHER', max_length=20, verbose_name='Тип титула')),
                ('awarded_at', models.DateField(blank=True, null=True, verbose_name='Дата присвоения')),
                ('remark', models.TextField(blank=True, verbose_name='Примечание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
            ],
            options={
                'verbose_name': 'Титул',
                'verbose_name_plural': 'Титулы',
                'ordering': ['abbreviation'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_name', models.CharField(db_index=True, max_length=200, verbose_name='Официальное имя (родословная)')),
                ('call_name', models.CharField(blank=True, max_length=100, verbose_name='Домашнее имя')),
                ('sex', models.CharField(choices=[('M', 'Самец'), ('F', 'Самка')], max_length=1, verbose_name='Пол')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('death_date', models.DateField(blank=True, null=True, verbose_name='Дата смерти')),
                ('microchip', models.CharField(blank=True, max_length=50, verbose_name='Микрочип')),
                ('pedigree_number', models.CharField(blank=True, max_length=100, verbose_name='Номер родословной')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_for_breeding', models.BooleanField(default=True, verbose_name='Допущен к разведению')),
                ('remark', models.TextField(blank=True, verbose_name='Примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cats', to='cats.breed', verbose_name='Порода')),
                ('father', models.ForeignKey(blank=True, limit_choices_to={'sex': 'M'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kittens_from_father', to='cats.cat', verbose_name='Отец')),
                ('mother', models.ForeignKey(blank=True, limit_choices_to={'sex': 'F'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kittens_from_mother', to='cats.cat', verbose_name='Мать')),
            ],
            options={
                'verbose_name': 'Кот',
                'verbose_name_plural': 'Коты',
                'ordering': ['registered_name'],
            },
        ),
        migrations.CreateModel(
            name='CatName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('language_code', models.CharField(blank=True, help_text='ru, de, en и т.д.', max_length=10)),
                ('is_official', models.BooleanField(default=False, help_text='Основное отображаемое имя')),
                ('remark', models.TextField(blank=True)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='names', to='cats.cat')),
            ],
            options={
                'ordering': ['-is_official', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Cattery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(blank=True, max_length=100, verbose_name='Регистрационный номер')),
                ('prefix', models.CharField(blank=True, max_length=100, verbose_name='Зарегистрированный префикс')),
                ('suffix', models.CharField(blank=True, max_length=100, verbose_name='Зарегистрированный суффикс')),
                ('founded_year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Год основания')),
                ('website', models.URLField(blank=True, verbose_name='Веб-сайт')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('remark', models.TextField(blank=True, verbose_name='Примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catteries', to='cats.address', verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Питомник',
                'verbose_name_plural': 'Питомники',
                'ordering': ['translations__name'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name='cat',
            name='cattery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cats', to='cats.cattery', verbose_name='Питомник рождения'),
        ),
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cats.city'),
        ),
        migrations.CreateModel(
            name='CatColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ems_code', models.CharField(max_length=50, verbose_name='EMS code')),
                ('cat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cat_color', to='cats.cat')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cat_colors', to='cats.color')),
                ('components', models.ManyToManyField(related_name='cat_colors', to='cats.colorcomponent')),
            ],
            options={
                'verbose_name': 'Cat Color',
                'verbose_name_plural': 'Cat Colors',
            },
        ),
        migrations.AddField(
            model_name='colorcomponent',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='components', to='cats.colorcomponenttype'),
        ),
        migrations.CreateModel(
            name='ColorComponentUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(help_text='Position in EMS formula')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_usages', to='cats.color')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cats.colorcomponent')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('color', 'component')},
            },
        ),
        migrations.AddField(
            model_name='color',
            name='components',
            field=models.ManyToManyField(related_name='colors', through='cats.ColorComponentUsage', to='cats.colorcomponent'),
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='cats.country'),
        ),
        migrations.AddField(
            model_name='address',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cats.country'),
        ),
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('VACCINATION', 'Прививка'), ('ILLNESS', 'Болезнь'), ('CHECKUP', 'Обследование'), ('OTHER', 'Другое')], default='OTHER', max_length=20, verbose_name='Тип записи')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('date', models.DateField(verbose_name='Дата записи')),
                ('remark', models.TextField(blank=True, verbose_name='Примечание')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to='cats.cat')),
            ],
            options={
                'verbose_name': 'Запись о здоровье',
                'verbose_name_plural': 'Записи о здоровье',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Litter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('litter_code', models.CharField(max_length=50, unique=True, verbose_name='Код помёта')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('kittens_count', models.PositiveSmallIntegerField(default=0, verbose_name='Количество котят')),
                ('remark', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cattery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='litters', to='cats.cattery', verbose_name='Питомник')),
                ('father', models.ForeignKey(limit_choices_to={'sex': 'M'}, on_delete=django.db.models.deletion.PROTECT, related_name='litters_as_father', to='cats.cat', verbose_name='Отец')),
                ('mother', models.ForeignKey(limit_choices_to={'sex': 'F'}, on_delete=django.db.models.deletion.PROTECT, related_name='litters_as_mother', to='cats.cat', verbose_name='Мать')),
            ],
            options={
                'verbose_name': 'Помёт',
                'verbose_name_plural': 'Помёты',
                'ordering': ['-birth_date'],
            },
        ),
        migrations.AddField(
            model_name='cat',
            name='litter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kittens', to='cats.litter', verbose_name='Помёт'),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('object_id', models.PositiveIntegerField()),
                ('doc_type', models.CharField(blank=True, max_length=50, verbose_name='Тип документа (родословная, договор и т.д.)')),
                ('is_public', models.BooleanField(default=False, verbose_name='Публичный')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cats.mediafile')),
            ],
        ),
        migrations.CreateModel(
            name='MediaLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('role', models.CharField(blank=True, help_text='photo, pedigree, contract, etc.', max_length=50)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cats.mediafile')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Код / аббревиатура')),
                ('website', models.URLField(blank=True, verbose_name='Веб-сайт')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('org_type', models.CharField(choices=[('SYSTEM', 'Международная система'), ('FEDERATION', 'Федерация'), ('CLUB', 'Клуб'), ('OTHER', 'Другое')], default='CLUB', max_length=20, verbose_name='Тип организации')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('remark', models.TextField(blank=True, verbose_name='Примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizations', to='cats.address', verbose_name='Адрес')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suborganizations', to='cats.organization', verbose_name='Родительская организация')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
                'ordering': ['code'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cats.address')),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_type', models.CharField(choices=[('BREEDER', 'Заводчик'), ('ASSISTANT', 'Помощник'), ('JUDGE', 'Судья'), ('OTHER', 'Другое')], default='BREEDER', max_length=20, verbose_name='Тип членства')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('remark', models.TextField(blank=True, verbose_name='Примечание')),
                ('cattery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memberships', to='cats.cattery', verbose_name='Питомник')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='cats.organization', verbose_name='Организация')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memberships', to='cats.person', verbose_name='Член (человек)')),
            ],
            options={
                'verbose_name': 'Членство',
                'verbose_name_plural': 'Членства',
                'ordering': ['organization', 'cattery', 'person'],
            },
        ),
        migrations.AddField(
            model_name='cattery',
            name='owners',
            field=models.ManyToManyField(blank=True, related_name='catteries', to='cats.person', verbose_name='Владельцы'),
        ),
        migrations.AddField(
            model_name='cat',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_cats', to='cats.person'),
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='cats.country')),
            ],
            options={
                'ordering': ['country', 'code'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name='city',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cities', to='cats.region'),
        ),
        migrations.AddField(
            model_name='address',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cats.region'),
        ),
        migrations.CreateModel(
            name='RegionTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=200)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='cats.region')),
            ],
            options={
                'verbose_name': 'region Translation',
                'db_table': 'cats_region_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TitleTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('full_name', models.CharField(max_length=200, verbose_name='Полное название титула')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='cats.title')),
            ],
            options={
                'verbose_name': 'Титул Translation',
                'db_table': 'cats_title_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='BreedTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=200, verbose_name='Breed name')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='cats.breed')),
            ],
            options={
                'verbose_name': 'Breed Translation',
                'db_table': 'cats_breed_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CatteryTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=200, verbose_name='Название питомника')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='cats.cattery')),
            ],
            options={
                'verbose_name': 'Питомник Translation',
                'db_table': 'cats_cattery_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CityTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=200)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='cats.city')),
            ],
            options={
                'verbose_name': 'city Translation',
                'db_table': 'cats_city_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ColorComponentTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=100, verbose_name='Component name')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='cats.colorcomponent')),
            ],
            options={
                'verbose_name': 'Color Component Translation',
                'db_table': 'cats_colorcomponent_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.AlterUniqueTogether(
            name='colorcomponent',
            unique_together={('type', 'code')},
        ),
        migrations.CreateModel(
            name='ColorComponentTypeTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=100, verbose_name='Component type')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='cats.colorcomponenttype')),
            ],
            options={
                'verbose_name': 'Color Component Type Translation',
                'db_table': 'cats_colorcomponenttype_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ColorTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=200, verbose_name='Color name')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='cats.color')),
            ],
            options={
                'verbose_name': 'Color Translation',
                'db_table': 'cats_color_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CountryTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=200)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='cats.country')),
            ],
            options={
                'verbose_name': 'country Translation',
                'db_table': 'cats_country_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='OrganizationTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=200, verbose_name='Название организации')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='cats.organization')),
            ],
            options={
                'verbose_name': 'Организация Translation',
                'db_table': 'cats_organization_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.AddConstraint(
            model_name='cat',
            constraint=models.UniqueConstraint(fields=('registered_name', 'cattery'), name='unique_name_per_cattery'),
        ),
        migrations.AlterUniqueTogether(
            name='region',
            unique_together={('country', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='regiontranslation',
            unique_together={('language_code', 'master')},
        ),
        migrations.AlterUniqueTogether(
            name='titletranslation',
            unique_together={('language_code', 'master')},
        ),
    ]
