# Generated by Django 6.0.2 on 2026-03-14 14:40

import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0002_color_colortranslation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ColorComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='EMS code')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Order in EMS formula')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Color Component',
                'verbose_name_plural': 'Color Components',
                'ordering': ['type__order', 'order', 'code'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ColorComponentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Order in EMS formula')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Color Component Type',
                'verbose_name_plural': 'Color Component Types',
                'ordering': ['order', 'code'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CatColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ems_code', models.CharField(max_length=50, verbose_name='EMS code')),
                ('cat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cat_color', to='cats.cat')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cat_colors', to='cats.color')),
                ('components', models.ManyToManyField(related_name='cat_colors', to='cats.colorcomponent')),
            ],
            options={
                'verbose_name': 'Cat Color',
                'verbose_name_plural': 'Cat Colors',
            },
        ),
        migrations.AddField(
            model_name='colorcomponent',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='components', to='cats.colorcomponenttype'),
        ),
        migrations.CreateModel(
            name='ColorComponentTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=100, verbose_name='Component name')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='cats.colorcomponent')),
            ],
            options={
                'verbose_name': 'Color Component Translation',
                'db_table': 'cats_colorcomponent_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.AlterUniqueTogether(
            name='colorcomponent',
            unique_together={('type', 'code')},
        ),
        migrations.CreateModel(
            name='ColorComponentTypeTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=100, verbose_name='Component type')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='cats.colorcomponenttype')),
            ],
            options={
                'verbose_name': 'Color Component Type Translation',
                'db_table': 'cats_colorcomponenttype_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
