# Generated by Django 6.0.2 on 2026-03-30 06:09

import cats.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0003_alter_document_options_alter_mediafile_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediafile',
            name='file',
            field=models.FileField(upload_to=cats.models.upload_to_media),
        ),
    ]
