# Generated by Django 6.0.2 on 2026-03-14 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0003_cat_colorcomponent_colorcomponenttype_catcolor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='colorcomponenttype',
            name='remark',
            field=models.CharField(blank=True, max_length=255, verbose_name='Remark (for internal use)'),
        ),
    ]
