# Generated by Django 6.0.2 on 2026-03-14 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0004_colorcomponenttype_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='remark',
            field=models.CharField(blank=True, max_length=255, verbose_name='Remark (for internal use)'),
        ),
    ]
