# Generated by Django 6.0.3 on 2026-04-01 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0004_alter_mediafile_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medialink',
            options={'ordering': ['sort_order', '-id']},
        ),
        migrations.AddField(
            model_name='cat',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Показывать на витрине'),
        ),
        migrations.AddField(
            model_name='medialink',
            name='is_primary',
            field=models.BooleanField(default=False, verbose_name='Главное фото'),
        ),
        migrations.AddField(
            model_name='medialink',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
    ]
