# Generated by Django 6.0.3 on 2026-04-01 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0005_alter_medialink_options_cat_is_featured_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catcolor',
            name='components',
            field=models.ManyToManyField(blank=True, related_name='cat_colors', to='cats.colorcomponent'),
        ),
        migrations.AlterField(
            model_name='catcolor',
            name='ems_code',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='EMS code'),
        ),
        migrations.AddConstraint(
            model_name='cat',
            constraint=models.UniqueConstraint(condition=models.Q(('microchip', ''), _negated=True), fields=('microchip',), name='unique_nonempty_microchip'),
        ),
        migrations.AddConstraint(
            model_name='cat',
            constraint=models.UniqueConstraint(condition=models.Q(('pedigree_number', ''), _negated=True), fields=('pedigree_number',), name='unique_nonempty_pedigree_number'),
        ),
    ]
