# Generated by Django 6.0.3 on 2026-04-01 17:36

import cats.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0006_alter_catcolor_components_alter_catcolor_ems_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colortranslation',
            name='name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Color name'),
        ),
        migrations.CreateModel(
            name='CatPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=cats.models.upload_to_cat_photo, verbose_name='Фотография')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Главное фото')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='cats.cat', verbose_name='Кот')),
            ],
            options={
                'verbose_name': 'Фото кота',
                'verbose_name_plural': 'Фотографии котов',
                'ordering': ['sort_order', '-is_primary', '-uploaded_at'],
            },
        ),
    ]
