# Generated by Django 6.0.2 on 2026-03-14 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0006_colorcomponent_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='remark',
            field=models.TextField(blank=True, verbose_name='Remark (for internal use)'),
        ),
        migrations.AlterField(
            model_name='colorcomponent',
            name='remark',
            field=models.TextField(blank=True, verbose_name='Remark (for internal use)'),
        ),
        migrations.AlterField(
            model_name='colorcomponenttype',
            name='remark',
            field=models.TextField(blank=True, verbose_name='Remark (for internal use)'),
        ),
    ]
