# Generated by Django 6.0.3 on 2026-04-03 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0007_alter_colortranslation_name_catphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='litter',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Снимите галочку когда все котята разъехались', verbose_name='Активный помёт'),
        ),
    ]
