# Generated by Django 6.0.2 on 2026-03-15 10:34

import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0007_alter_color_remark_alter_colorcomponent_remark_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=255)),
                ('house_number', models.CharField(blank=True, max_length=20)),
                ('apartment', models.CharField(blank=True, max_length=20)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('remark', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['country', 'region', 'translations__name'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso_code', models.CharField(help_text='ISO 3166-1 alpha-2', max_length=2, unique=True)),
                ('phone_code', models.CharField(blank=True, max_length=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['iso_code'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='media/')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_public', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbreviation', models.CharField(max_length=20, unique=True, verbose_name='Аббревиатура титула')),
                ('title_type', models.CharField(choices=[('CHAMPION', 'Чемпион'), ('INTERCHAMPION', 'Интерчемпион'), ('NATIONAL', 'Национальный титул'), ('WORLD', 'Мировой титул'), ('OTHER', 'Другое')], default='OTHER', max_length=20, verbose_name='Тип титула')),
                ('awarded_at', models.DateField(blank=True, null=True, verbose_name='Дата присвоения')),
                ('remark', models.TextField(blank=True, verbose_name='Примечание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
            ],
            options={
                'verbose_name': 'Титул',
                'verbose_name_plural': 'Титулы',
                'ordering': ['abbreviation'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Cattery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(blank=True, max_length=100, verbose_name='Регистрационный номер')),
                ('prefix', models.CharField(blank=True, max_length=100, verbose_name='Зарегистрированный префикс')),
                ('suffix', models.CharField(blank=True, max_length=100, verbose_name='Зарегистрированный суффикс')),
                ('founded_year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Год основания')),
                ('website', models.URLField(blank=True, verbose_name='Веб-сайт')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('remark', models.TextField(blank=True, verbose_name='Примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catteries', to='cats.address', verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Питомник',
                'verbose_name_plural': 'Питомники',
                'ordering': ['translations__name'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cats.city'),
        ),
        migrations.CreateModel(
            name='ColorComponentUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(help_text='Position in EMS formula')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_usages', to='cats.color')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cats.colorcomponent')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('color', 'component')},
            },
        ),
        migrations.AddField(
            model_name='color',
            name='components',
            field=models.ManyToManyField(related_name='colors', through='cats.ColorComponentUsage', to='cats.colorcomponent'),
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='cats.country'),
        ),
        migrations.AddField(
            model_name='address',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cats.country'),
        ),
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('VACCINATION', 'Прививка'), ('ILLNESS', 'Болезнь'), ('CHECKUP', 'Обследование'), ('OTHER', 'Другое')], default='OTHER', max_length=20, verbose_name='Тип записи')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('date', models.DateField(verbose_name='Дата записи')),
                ('remark', models.TextField(blank=True, verbose_name='Примечание')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to='cats.cat')),
            ],
            options={
                'verbose_name': 'Запись о здоровье',
                'verbose_name_plural': 'Записи о здоровье',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('object_id', models.PositiveIntegerField()),
                ('doc_type', models.CharField(blank=True, max_length=50, verbose_name='Тип документа (родословная, договор и т.д.)')),
                ('is_public', models.BooleanField(default=False, verbose_name='Публичный')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cats.mediafile')),
            ],
        ),
        migrations.CreateModel(
            name='MediaLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('role', models.CharField(blank=True, help_text='photo, pedigree, contract, etc.', max_length=50)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cats.mediafile')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Код / аббревиатура')),
                ('website', models.URLField(blank=True, verbose_name='Веб-сайт')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('org_type', models.CharField(choices=[('SYSTEM', 'Международная система'), ('FEDERATION', 'Федерация'), ('CLUB', 'Клуб'), ('OTHER', 'Другое')], default='CLUB', max_length=20, verbose_name='Тип организации')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('remark', models.TextField(blank=True, verbose_name='Примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizations', to='cats.address', verbose_name='Адрес')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suborganizations', to='cats.organization', verbose_name='Родительская организация')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
                'ordering': ['code'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cats.address')),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_type', models.CharField(choices=[('BREEDER', 'Заводчик'), ('ASSISTANT', 'Помощник'), ('JUDGE', 'Судья'), ('OTHER', 'Другое')], default='BREEDER', max_length=20, verbose_name='Тип членства')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('remark', models.TextField(blank=True, verbose_name='Примечание')),
                ('cattery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memberships', to='cats.cattery', verbose_name='Питомник')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='cats.organization', verbose_name='Организация')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memberships', to='cats.person', verbose_name='Член (человек)')),
            ],
            options={
                'verbose_name': 'Членство',
                'verbose_name_plural': 'Членства',
                'ordering': ['organization', 'cattery', 'person'],
            },
        ),
        migrations.AddField(
            model_name='cattery',
            name='owners',
            field=models.ManyToManyField(blank=True, related_name='catteries', to='cats.person', verbose_name='Владельцы'),
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='cats.country')),
            ],
            options={
                'ordering': ['country', 'code'],
                'unique_together': {('country', 'code')},
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name='city',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cities', to='cats.region'),
        ),
        migrations.AddField(
            model_name='address',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cats.region'),
        ),
        migrations.CreateModel(
            name='CatteryTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=200, verbose_name='Название питомника')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='cats.cattery')),
            ],
            options={
                'verbose_name': 'Питомник Translation',
                'db_table': 'cats_cattery_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CityTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=200)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='cats.city')),
            ],
            options={
                'verbose_name': 'city Translation',
                'db_table': 'cats_city_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CountryTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=200)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='cats.country')),
            ],
            options={
                'verbose_name': 'country Translation',
                'db_table': 'cats_country_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='OrganizationTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=200, verbose_name='Название организации')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='cats.organization')),
            ],
            options={
                'verbose_name': 'Организация Translation',
                'db_table': 'cats_organization_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='RegionTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=200)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='cats.region')),
            ],
            options={
                'verbose_name': 'region Translation',
                'db_table': 'cats_region_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TitleTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('full_name', models.CharField(max_length=200, verbose_name='Полное название титула')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='cats.title')),
            ],
            options={
                'verbose_name': 'Титул Translation',
                'db_table': 'cats_title_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
