# Generated by Django 6.0.3 on 2026-04-03 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0008_litter_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='facebook',
            field=models.URLField(blank=True, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='person',
            name='instagram',
            field=models.URLField(blank=True, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='person',
            name='tiktok',
            field=models.URLField(blank=True, verbose_name='TikTok'),
        ),
        migrations.AddField(
            model_name='person',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='Номер телефона с кодом страны, например +491234567890', max_length=30, verbose_name='WhatsApp'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='sex',
            field=models.CharField(choices=[('M', 'Кот'), ('F', 'Кошка')], max_length=1, verbose_name='Пол'),
        ),
    ]
