# Generated by Django 6.0.3 on 2026-04-04 08:44

import cats.models
import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0009_person_facebook_person_instagram_person_tiktok_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('LIFE', 'Повседневная жизнь'), ('LITTER', 'Помёты'), ('ART', 'Художественные')], default='LIFE', max_length=20, verbose_name='Категория')),
                ('cover', models.ImageField(blank=True, null=True, upload_to=cats.models.upload_to_gallery, verbose_name='Обложка альбома')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('litter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallery_albums', to='cats.litter', verbose_name='Помёт (если альбом помёта)')),
            ],
            options={
                'verbose_name': 'Альбом галереи',
                'verbose_name_plural': 'Альбомы галереи',
                'ordering': ['-date', '-created_at'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='GalleryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=cats.models.upload_to_gallery, verbose_name='Фото')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Подпись')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Ссылка на пост Instagram')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='cats.galleryalbum', verbose_name='Альбом')),
            ],
            options={
                'verbose_name': 'Фото галереи',
                'verbose_name_plural': 'Фото галереи',
                'ordering': ['sort_order', '-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('LIFE', 'Повседневная жизнь'), ('LITTER', 'Котята и помёты'), ('OTHER', 'Разное')], default='LIFE', max_length=20, verbose_name='Категория')),
                ('video_url', models.URLField(blank=True, help_text='Например: https://www.youtube.com/watch?v=XXXXX', verbose_name='Ссылка на YouTube / Vimeo')),
                ('video_file', models.FileField(blank=True, help_text='Только для коротких клипов до 50 МБ', null=True, upload_to=cats.models.upload_to_video_file, verbose_name='Видеофайл (mp4)')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=cats.models.upload_to_video_thumb, verbose_name='Превью')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата съёмки')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('litter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='cats.litter', verbose_name='Помёт')),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видео',
                'ordering': ['-date', '-created_at'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='GalleryAlbumTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=200, verbose_name='Название альбома')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='cats.galleryalbum')),
            ],
            options={
                'verbose_name': 'Альбом галереи Translation',
                'db_table': 'cats_galleryalbum_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='VideoTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='cats.video')),
            ],
            options={
                'verbose_name': 'Видео Translation',
                'db_table': 'cats_video_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
